# Generated by Django 4.0.6 on 2022-07-09 12:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_board_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board_comments',
            name='comment_id',
            field=models.ForeignKey(db_column='comment_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comment', to='board.board_comments'),
        ),
    ]
