# Generated by Django 4.0.6 on 2022-07-09 15:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('board', '0003_alter_board_comments_comment_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='board_comments',
            name='order',
        ),
        migrations.AlterField(
            model_name='board_comments',
            name='comment_id',
            field=models.ForeignKey(blank=True, db_column='comment_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reply', to='board.board_comments'),
        ),
        migrations.AlterField(
            model_name='board_comments',
            name='writer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='writers', to=settings.AUTH_USER_MODEL),
        ),
    ]
